 include: package:lint/analysis_options.yaml

 linter:
   rules:
     # ------ Disable individual rules ----- #
     #                 ---                   #
     # Turn off what you don't like.         #
     # ------------------------------------- #

     avoid_classes_with_only_static_members: false
     prefer_const_literals_to_create_immutables: false